[metadata]
name = "Tol Light"
category = "color"
description = "Paul Tol's light 9-color qualitative palette, suitable for light backgrounds."

[rcparams]
_palette = ["#77AADD", "#99DDFF", "#44BB99", "#BBCC33", "#AAAA00", "#EEDD88", "#EE8866", "#FFAABB", "#DDDDDD"]
