[metadata]
name = "Tol Rainbow 12"
category = "color"
description = "Paul Tol's discrete rainbow palette sampled at 12 colors."

[rcparams]
_palette = ["#332288", "#88CCEE", "#44AA99", "#117733", "#999933", "#DDCC77", "#EE8866", "#CC6677", "#AA4499", "#882255", "#EE6677", "#EEDD88"]
