# -- Project information -------------------------------------------------------

import importlib.metadata
import os

project = "plotstyle"
author = "Rahul Kaushal"
copyright = "2026, Rahul Kaushal"

release = importlib.metadata.version("plotstyle")
version = ".".join(release.split(".")[:2])

# -- General configuration -----------------------------------------------------

extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "myst_parser",
    "sphinx_autodoc_typehints",
    "sphinx_copybutton",
]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# -- MyST (Markdown) settings --------------------------------------------------

myst_enable_extensions = [
    "colon_fence",
    "fieldlist",
    "deflist",
]
myst_heading_anchors = 3

# -- Autodoc / autosummary settings --------------------------------------------

autodoc_member_order = "bysource"
autodoc_typehints = "description"
autosummary_generate = True

# -- Napoleon (NumPy + Google docstring) settings ------------------------------

napoleon_numpy_docstring = True
napoleon_google_docstring = True  # hybrid style: Args: (Google) + Returns/Raises (NumPy)
napoleon_use_rtype = False
napoleon_use_param = True
napoleon_preprocess_types = True

# -- Intersphinx ---------------------------------------------------------------

intersphinx_mapping: dict = {
    "python": ("https://docs.python.org/3", None),
}

# External inventories require trusted TLS; on RTD this always works.
# Local builds behind corporate proxies may fail, so we only enable
# the full set when running on RTD or when INTERSPHINX_FULL is set.
if os.environ.get("READTHEDOCS") or os.environ.get("INTERSPHINX_FULL"):
    intersphinx_mapping.update(
        {
            "matplotlib": ("https://matplotlib.org/stable/", None),
            "numpy": ("https://numpy.org/doc/stable/", None),
            "seaborn": ("https://seaborn.pydata.org/", None),
        }
    )

intersphinx_timeout = 5  # seconds; avoids long hangs behind proxies

# -- Suppress warnings ---------------------------------------------------------

suppress_warnings = [
    # Benign RST formatting in auto-generated content from autodoc + napoleon
    # for frozen dataclass attribute sections.  Does not affect HTML output.
    "docutils",
]

# Silence nitpicky cross-reference warnings for targets that are intentionally
# not documented (numpy internal types, generated by sphinx_autodoc_typehints).
nitpick_ignore = [
    ("py:class", "numpy.float64"),
]

# Regex-based suppression for categories of cross-reference targets that
# sphinx_autodoc_typehints / Napoleon auto-generates from type annotations
# but that are not registered in any Sphinx inventory:
#
#  • Generic container types  — list[T], dict[K,V], tuple[...], etc.
#  • Union / Optional forms   — X | Y, str | None, etc.
#  • Orphaned bracket fragments caused by multi-element tuple splitting
#    (e.g. "tuple[Figure, Axes]"  →  "tuple[Figure"  +  "Axes]")
#  • Matplotlib Figure / Axes  — only available in RTD / INTERSPHINX_FULL mode
#  • NumPy NDArray aliases     — NDArray[np.float64] etc.
#  • pathlib.Path unqualified  — "Path" alone is not in the Python inventory
#  • Internal plotstyle types  — PaletteResult, JournalSpec, ValidationReport,
#                                CheckResult referenced by short name from Napoleon
nitpick_ignore_regex = [
    # Generic containers: list[...], dict[...], tuple[...], set[...], etc.
    (r"py:class", r"(list|dict|tuple|set|frozenset)\[.*"),
    # Union types:  str | None,  float | None,  X | Y  (any variant)
    (r"py:class", r".*\s*\|\s*.*"),
    # Orphaned closing-bracket fragments (e.g. "Axes]", "Any]", "float]]")
    (r"py:class", r"^[^\[]*\]+\s*$"),
    # NumPy typed array aliases and fully-qualified numpy types
    (r"py:class", r"NDArray.*"),
    (r"py:class", r"numpy\..*"),
    # Matplotlib types — intersphinx only loaded on RTD / INTERSPHINX_FULL;
    # matches both bare names ("Figure") and fully-qualified forms
    # ("matplotlib.figure.Figure", "matplotlib.axes._axes.Axes").
    (r"py:class", r"Figure"),
    (r"py:class", r"Axes"),
    (r"py:class", r"matplotlib\..*"),
    (r"py:meth", r"matplotlib\..*"),
    (r"py:func", r"matplotlib\..*"),
    # pathlib.Path — intersphinx entry is "pathlib.Path", not bare "Path"
    (r"py:class", r"Path"),
    # Internal plotstyle types referenced by unqualified short name
    (r"py:class", r"PaletteResult"),
    (r"py:class", r"JournalSpec"),
    (r"py:class", r"ValidationReport"),
    (r"py:class", r"CheckResult"),
    (r"py:class", r"StyleOverlay"),
]

# -- HTML theme ----------------------------------------------------------------

html_theme = "furo"
html_static_path = ["_static"]
html_css_files = ["custom.css"]

html_theme_options = {
    "source_repository": "https://github.com/rahulkaushal04/plotstyle",
    "source_branch": "main",
    "source_directory": "docs/",
}

# -- Source suffix -------------------------------------------------------------

source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}
